import { GoogleGenerativeAI } from "@google/generative-ai";
import fs from "fs";
import path from "path";
import { userToCharacterMapWarhammer } from "./createListeningStream";
const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) throw new Error("Missing GEMINI_API_KEY");

const genAI = new GoogleGenerativeAI(apiKey);
// Helper: Convert total milliseconds back to [HH:MM:SS.mmm]
function formatTimeFromMs(totalMs: number): string {
	const d = new Date(totalMs);
	// We use UTC so timezone offsets don't mess up our math
	const h = String(d.getUTCHours()).padStart(2, "0");
	const m = String(d.getUTCMinutes()).padStart(2, "0");
	const s = String(d.getUTCSeconds()).padStart(2, "0");
	const ms = String(d.getUTCMilliseconds()).padStart(3, "0");
	return `[${h}:${m}:${s}.${ms}]`;
}

interface DialogueLine {
	absoluteMs: number;
	formattedTime: string;
	speaker: string;
	text: string;
}

export async function mergeAndCorrect(dateFolder: string) {
	const folderPath = path.join(process.cwd(), "transcriptions", dateFolder);
	const files = fs.readdirSync(folderPath).filter((f) => f.endsWith(".json"));

	if (files.length === 0) return console.log("No Whisper JSON files found.");

	const allDialogue: DialogueLine[] = [];

	console.log(
		"🧩 Parsing Whisper JSON files and calculating absolute timestamps...",
	);

	// 1. Parse every JSON file and calculate the exact wall-clock time of every word
	for (const file of files) {
		const filePath = path.join(folderPath, file);

		// Extract base time and user
		// Filename format: 193428.125-123456789.wav.json
		const baseTimeMs = parseInt(file.split("-")[0]!, 10);
		const userId = file.split("-")[1]!.split(".")[0]!;
		const speakerName =
			userToCharacterMapWarhammer[userId] || `Unknown (${userId})`;

		// Read Whisper JSON output
		const rawData = fs.readFileSync(filePath, "utf-8");
		const whisperData = JSON.parse(rawData);

		// whisper.cpp puts segments inside the "transcription" array.
		// "offsets.from" is usually in milliseconds from the start of the audio clip.
		const segments = whisperData.transcription || whisperData.segments || [];

		for (const segment of segments) {
			// Get relative offset (e.g., this word was spoken 1500ms into the clip)
			const relativeStartMs = segment.offsets?.from ?? segment.t0 * 10;

			// Calculate Absolute Time
			const absoluteMs = baseTimeMs + relativeStartMs;

			allDialogue.push({
				absoluteMs,
				formattedTime: formatTimeFromMs(absoluteMs),
				speaker: speakerName,
				text: segment.text.trim(),
			});
		}
	}

	// 2. Sort EVERYTHING chronologically
	allDialogue.sort((a, b) => a.absoluteMs - b.absoluteMs);

	// Create a raw transcript
	let rawTranscript = "";
	for (const line of allDialogue) {
		rawTranscript += `${line.formattedTime} ${line.speaker}: ${line.text}\n`;
	}

	fs.writeFileSync(
		path.join(folderPath, "Raw_Whisper_Timeline.txt"),
		rawTranscript,
	);
	console.log("✅ Raw timeline merged and saved!");
	return;
	// 3. Send the raw text to Gemini for Correction & OOC Tagging
	// We can use Gemini 1.5 Flash here because text processing is very easy for it
	console.log(
		"🧠 Sending raw text to Gemini for formatting, D&D correction, and [OOC] tagging...",
	);
	const model = genAI.getGenerativeModel({
		model: "gemini-3.1-flash-lite-preview",
	});

	const prompt = `
You are an expert editor for a D&D session transcript.
I am providing you a chronologically merged raw transcript generated by Whisper. 
Because Whisper is just an audio transcriber, it has spelling errors, broken sentences, and no context.

YOUR JOB:
1. FIX ERRORS: Fix typos, especially fantasy names, Polish slang, or D&D terminology.
2. MERGE: If a speaker's sentence is broken across multiple timestamps, combine it so it reads naturally, keeping the start timestamp.
3. OOC TAGS: Determine if the dialogue is in-character roleplay or out-of-character (OOC) table talk. Add[OOC] after their name if it's table talk.
4. DM CHARACTERS: If the speaker is "DM", figure out what NPC they are playing based on context and format it as: DM (NPC Name).
5. DO NOT SUMMARIZE. DO NOT INVENT DIALOGUE. Keep the timestamps intact.

RAW TRANSCRIPT:
${rawTranscript}
`;

	// try {
	// 	const result = await model.generateContent(prompt);
	// 	const finalTranscript = result.response.text();

	// 	fs.writeFileSync(
	// 		path.join(folderPath, "Final_Corrected_Transcript.txt"),
	// 		finalTranscript,
	// 	);
	// 	console.log("🎉 Final Corrected Transcript Saved!");
	// } catch (err) {
	// 	console.error("AI Correction Failed:", err);
	// }
}

if (import.meta.main) {
	const targetFolder = process.argv[2];
	if (!targetFolder) process.exit(1);
	mergeAndCorrect(targetFolder);
}
